### ISSUE TITLE
configure multiple zones in nsd.conf

### ISSUE THREAD

**Issue by PhilippKuntschik** [The-Kube-Way/nsd#5]
Hey @fl42,

Thanks for the work! I finally got it to work in my kubernetes cluster, although there have to be some changes made for kubernetes version 1.25 that I could provide a pull request for in the future.

My question is about configuring zones, and if it is possible to [define multiple zones in the nsd-conf](https://github.com/The-Kube-Way/nsd/blob/master/docs/KUBERNETES.md?plain=1#L134-L137). I found some examples [online](https://dnswatch.com/dns-docs/NSD/), but they just use a format that seems to be invalid for yaml syntax (having duplicate keys). Do you know how I could provide multiple zones?

My use case is having a zone `dev` and a zone `prod` on the same nsd-server

**Comment by fl42** [comment]
Hello,

Could you please post your nsd-config ConfigMap object? (without personal information)
nsd.conf key is defined as string, so YAML syntax of the content should not be checked...

**Comment by PhilippKuntschik** [comment]
thanks,
> nsd.conf key is defined as string

that actually helped. if you want to declare multiple zones, you can do so with the following config. What I did wrong was trying to define the zones as yaml array.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nsd-config
  labels:
    app: nsd
data:
  nsd.conf: |
    server:
      server-count: 1
      verbosity: 1
      zonesdir: "/zones"
      hide-version: yes
      statistics: 60
    zone:
      name: "domain.tld"
      zonefile: "domain.tld.signed"
    zone:
      name: "other.tld"
      zonefile: "other.tld.signed"
```
